export const endpoints = {
  user: '/user-resource/user',
  userProfile: '/user-resource/user/profile',
  locations: '/config/locations',
  vmImages: '/config/vm_images',
  hostPools: '/user-resource/host_pool/list',
  vm: '/user-resource/vm',
  vmList: '/user-resource/vm/list',
  vmStart: '/user-resource/vm/start',
  vmStop: '/user-resource/vm/stop',
  vmReinstall: '/user-resource/vm/reinstall',
  vmPassword: '/user-resource/vm/user',
  vmStorage: '/user-resource/vm/storage',
  vmBackup: '/user-resource/vm/backup',
  vmPublicIp: '/user-resource/vm/ip/public',
  billingAccounts: '/payment/billing_account/list',
  billingAccount: '/payment/billing_account',
  unpaidAmount: '/payment/billing_account/unpaid_amount',
  creditList: '/payment/credit/list',
  creditBuy: '/payment/credit/buy',
  creditInvoice: '/payment/credit/request_invoice',
  invoices: '/payment/invoice/list',
} as const;
